language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make test
after_success:
  - make docker_build
  - PASSWORD=${DOCKER_PASSWORD} make docker_push
deploy:
  provider: heroku
  app: fathomless-sea-19990
  api_key: $Heroku_key
